/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — smoke-tested by the deploy step (A5).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot */
        post: operations["forgot_auth_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_auth_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client Context
         * @description Resolve + authorize the caller against the `[client]` tenant (the central guard).
         *
         *     The console shell calls this on entry to confirm access and learn the caller's role.
         *     A non-member gets 404 (tenant existence isn't leaked); an owner-gated variant passes
         *     `require_membership(MembershipRole.owner)`.
         */
        get: operations["client_context__client__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brief */
        get: operations["get_brief__client__brief_get"];
        /** Put Brief */
        put: operations["put_brief__client__brief_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/brief/structure/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Structure Prompt
         * @description The exact system + input prompt `POST /brief/structure` would send — no LLM call, no spend.
         *
         *     Built from the same `build_messages(brief, icps)` the live call uses, so the prompt-preview
         *     popup always mirrors what actually reaches the model.
         */
        get: operations["preview_structure_prompt__client__brief_structure_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/brief/structure/system-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save System Prompt
         * @description Save the scoping system prompt for this client as the next `briefing` version (append-only).
         *
         *     The `prompt` table is the source of truth and never overwritten — every save (including 'reset
         *     to default') appends a new version; the latest is active. An empty body resets to the code
         *     default. `is_custom` reflects whether the saved text diverges from that default.
         */
        put: operations["save_system_prompt__client__brief_structure_system_prompt_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/brief/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Structure Brief
         * @description Kick off Brief (+ICPs) → ResearchSpec **asynchronously**; returns a job to poll (202).
         *
         *     Scoping runs DeepSeek V4 Pro with thinking + web search (~55-76s) — too slow for the 30s API
         *     Gateway sync cap — so the LLM call runs on a background worker and the client polls
         *     `GET /brief/structure/status` until `done`/`error`. A still-running job is returned as-is, so
         *     a double-click never double-spends. (B6, async — see domains/briefs/structuring.py.)
         */
        post: operations["structure_brief__client__brief_structure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/brief/structure/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Structure Status
         * @description The latest structuring job's status — polled until terminal. `idle` when none has run.
         */
        get: operations["structure_status__client__brief_structure_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/research-spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Research Spec
         * @description Latest ResearchSpec + version history for the Workspace review panel.
         */
        get: operations["get_research_spec__client__research_spec_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/icps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Icps */
        get: operations["list_icps__client__icps_get"];
        put?: never;
        /** Create Icp */
        post: operations["create_icp__client__icps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/icps/{icp_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Icp */
        put: operations["update_icp__client__icps__icp_id__put"];
        post?: never;
        /** Delete Icp */
        delete: operations["delete_icp__client__icps__icp_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prospects */
        get: operations["list_prospects__client__prospects_get"];
        put?: never;
        /**
         * Add Prospect
         * @description Stage-2 manual add — one person, `source=manual`, same suppression + scoring as sourced
         *     rows. `company_id` is resolved by domain; upserts on (tenant, identity_key).
         */
        post: operations["add_prospect__client__prospects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description Stage-1 review feed — companies for this client, best fit first.
         */
        get: operations["list_companies__client__companies_get"];
        put?: never;
        /**
         * Add Company
         * @description Stage-1 manual add — one company, `source=manual`, same schema + scoring as sourced rows.
         *
         *     Upserts on (tenant, domain) so a manual add of an existing company updates it in place.
         */
        post: operations["add_company__client__companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/companies/find-company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Company
         * @description Flow A — Apollo company search from the latest ResearchSpec → suppress → enrich → upsert.
         *
         *     The search params are the v3 `company_search_params` + `intent_filters` (already Apollo-shaped);
         *     existing-customer domains and same-batch dupes are dropped before any row is stored. Survivors
         *     are upserted (a previously-known company is re-stamped with its `apollo_org_id`, not skipped).
         *     Capped at `MAX_COMPANIES_PER_FIND` per request. Records one `research_run` (source=apollo).
         *
         *     Rows come back UNSCORED (`score=False`): fit-scoring a fresh batch is the slow step and would
         *     blow the 30s gateway cap, so the web app fires scoring in the background (chunked `/rescore`)
         *     and shows a per-row "Scoring…" status. The scoring spend is then booked under `rescore` runs.
         */
        post: operations["find_company__client__companies_find_company_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/companies/find-lookalikes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Lookalikes
         * @description Lookalike (C7) — find the next batch of peers of the selected stage-1 rows.
         *
         *     Apollo has no native lookalike API, so the selected rows' firmographics are aggregated
         *     HoldSlot-side (`lookalike.build_lookalike_filter`) into a normal company-search filter, then run
         *     through the same Flow-A tail as find-company. The tenant's existing domains are passed as
         *     `seen_domains`, so the seeds + any already-listed peers drop out → the result is the genuinely
         *     NEW *next* batch (≤`LOOKALIKE_LIMIT`, often fewer). The run is tagged `source=lookalike`; the
         *     new rows themselves keep `source=apollo`.
         *
         *     Rows come back UNSCORED (`score=False`): fit-scoring a batch of brand-new companies is the slow
         *     step and would exceed the 30s gateway cap, so the web app fires the scoring in the background
         *     (chunked `/rescore` calls) and shows a per-row "Scoring…" status until each lands.
         */
        post: operations["find_lookalikes__client__companies_find_lookalikes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/companies/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Select Companies
         * @description Stage stage-1 companies into Step 2 (`discovered` → `selected`) or remove them (`selected` or
         *     `people_found` → `discovered`).
         *
         *     `selected=True` only promotes `discovered` rows (an already-searched `people_found` row is left
         *     as-is). `selected=False` is the Step-2 "Remove" — it un-stages a `selected` row OR an already
         *     searched `people_found` row back to the stage-1 pool, so an Accepted company can be taken out
         *     of Step 2. Re-searching is by explicit id (find-people), so demoting never blocks a later find.
         */
        patch: operations["select_companies__client__companies_select_patch"];
        trace?: never;
    };
    "/{client}/fit-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview Fit Prompt
         * @description The exact system + input prompt a fit-score call would send — no LLM call, no spend.
         *
         *     `stage=company_fit` (default) previews Step-1 company scoring; `stage=prospect_fit` previews
         *     Step-2 people scoring. Each is built from the SAME function the live scorer uses, with the real
         *     targeting context from the DB, so the Fit-rubric modal mirrors what reaches the model.
         *     `sample_id` picks the sample row (company id or prospect id for the respective stage).
         */
        get: operations["preview_fit_prompt__client__fit_prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/companies/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescore Companies
         * @description Re-run company fit scoring for an explicit set of already-sourced companies (the Step-1
         *     selection), ignoring the `fit_score is None` gate that find-company uses. Run this after the
         *     rubric or the scoring prompt changes so existing rows reflect the new scoring.
         *
         *     Bounded by `MAX_COMPANIES_PER_FIND` (the 30s API-Gateway sync cap) — a larger selection is
         *     rejected, not silently truncated, so the caller never thinks rows were re-scored when they
         *     weren't. Each row is scored against ITS OWN ICP context (targeting is memoized per icp_id, so
         *     a mixed selection is scored correctly). Records one `research_run` (source=rescore) for cost.
         */
        post: operations["rescore_companies__client__companies_rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/companies/update-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Company Fields
         * @description 'Update Field' — re-enrich Apollo firmographics for an explicit set of selected companies
         *     (industry/size/country + the evidence study fields). This is the deliberate, on-demand credit
         *     spend; find-company only enriches NEW rows so an existing org is never re-enriched for free.
         *
         *     One `organizations/enrich` call per distinct domain (concurrent). Bounded by
         *     `MAX_COMPANIES_PER_FIND` (the 30s sync cap) — a larger selection is rejected, not truncated.
         */
        post: operations["update_company_fields__client__companies_update_fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/research-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Runs */
        get: operations["list_research_runs__client__research_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/sourcing-docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sourcing Docs
         * @description The two editable fit rubrics: `company_fit` (Step 1) and `prospect_fit` (Step 2).
         */
        get: operations["get_sourcing_docs__client__sourcing_docs_get"];
        put?: never;
        /**
         * Save Sourcing Doc
         * @description Append-only — save the founder's fit-rubric edit as the next version.
         */
        post: operations["save_sourcing_doc__client__sourcing_docs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/people/find-people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find People
         * @description Flow B — find people across the SELECTED companies (one api_search per org), 0 credits.
         *
         *     C0: search rows carry no `organization_id`, so we loop the selected orgs and pass one
         *     `organization_ids` per call — each person's `company_id` is known from the loop. Rows land
         *     `found` (no email yet), are fit-scored on what's known, and dedupe on `apollo_person_id`.
         *     Enrichment (the credit spend) is a separate, human-gated step (`/prospects/enrich`).
         *
         *     No per-company people cap: each org contributes everyone matching the Find Settings (up to
         *     Apollo's 100/call). Bounded per request only by `MAX_ORGS_PER_FIND` orgs and
         *     `MAX_PEOPLE_PER_FIND_RUN` total people (find is free + unscored, an I/O bound, not the LLM one).
         *     Every org
         *     actually searched advances to `people_found`; the operator re-runs to drain a large selection.
         */
        post: operations["find_people__client__people_find_people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/people/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * People Facets
         * @description Live Find-Settings facet sidebar — per Management-Level / Department people counts across the
         *     selected Step-2 companies (free; Apollo people search costs no credits). One probe per facet
         *     value, scoped to the union of selected orgs, run concurrently to stay under the 30s sync cap.
         *     Only the 14 master departments are probed (not the ~245 subs) so the call is a fixed 11 + 14 + 1
         *     searches regardless of how many companies are selected.
         */
        post: operations["people_facets__client__people_facets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/people/scope-override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get People Scope Override
         * @description The tenant's saved Step-2 Find Settings (people facets), or null params when none is saved
         *     (→ the Workspace shows the AI scope). Persisted server-side so it follows the operator across
         *     browsers/devices.
         */
        get: operations["get_people_scope_override__client__people_scope_override_get"];
        /**
         * Save People Scope Override
         * @description Save the Step-2 Find Settings as the tenant's people-scope override. It then wins over the AI
         *     spec on every Find People until reset.
         *
         *     An EMPTY payload (no seniority/department chosen) is a revert, not a save: it deletes any saved
         *     row so the next Find People falls back to the AI scope — same as the 'Reset to AI scope' button.
         *     Persisting an all-empty override would otherwise silently widen every search to the whole org.
         *     A non-empty payload is UPSERTed atomically (ON CONFLICT) so concurrent saves can't race the
         *     unique (tenant, kind) constraint into a 500.
         */
        put: operations["save_people_scope_override__client__people_scope_override_put"];
        post?: never;
        /**
         * Reset People Scope Override
         * @description Discard the saved Step-2 override → Find People reverts to the AI scope. Idempotent: a no-op
         *     when nothing is saved.
         */
        delete: operations["reset_people_scope_override__client__people_scope_override_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/people/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * People Departments
         * @description The 14 master Department & Job Function options (value + label) — the single source of truth
         *     for the Find-Settings department list before live counts load. Static (Apollo's taxonomy), no
         *     Apollo call, no spend; the frontend renders these so it never hardcodes the master list.
         */
        get: operations["people_departments__client__people_departments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/prospects/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescore Prospects
         * @description Step-2 'Get AI score' — re-run people fit scoring for an explicit set of prospects (by
         *     identity key), against the current rubric. Mirrors `rescore_companies`: people land unscored
         *     from find, so this is how a person gets a fit tier; re-running after a rubric change re-scores.
         *
         *     Bounded by `MAX_PEOPLE_PER_FIND` (the 30s sync cap) — a larger selection is rejected, not
         *     truncated. Each row scores against ITS OWN ICP context (targeting memoized per icp_id). Records
         *     one `research_run` (source=rescore) for cost.
         */
        post: operations["rescore_prospects__client__prospects_rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{client}/prospects/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Enrich
         * @description The enrich gate (C5) — Apollo `people/match` on the confirmed rows. The only credit spend.
         *
         *     Human-gated and **idempotent**: each Apollo-sourced row that isn't already enriched spends 1
         *     credit to reveal a verified email (phone off at MVP), is written back with email / last name /
         *     linkedin / departments, and moves to `scored`. Rows already enriched (email on file) or with no
         *     `apollo_person_id` (manual) are confirmed without a match call, so a re-submit never re-spends.
         *
         *     **Bounded + concurrent (the credit-safety contract):** at most `MAX_ENRICH_PER_REQUEST` keys per
         *     request (rejected, not truncated), so a single call can never run away with the credit pool or
         *     overrun the 30s cap. The paid `people/match` calls fan out on a thread pool (HTTP-only; ORM
         *     writes stay single-threaded), then results are applied + committed once. A per-row Apollo error
         *     is counted in `failed` and the row marked `enrich_failed` — the spend counts are always returned
         *     (never lost to a mid-batch 502), so the caller can reconcile exactly what was charged.
         */
        post: operations["confirm_enrich__client__prospects_enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BriefIn
         * @description The brief form document — an opaque key→value bag (churn-proof; no per-field schema).
         */
        BriefIn: {
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * BriefOut
         * @description The stored brief plus the server-computed completeness (single source of truth).
         */
        BriefOut: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Completeness */
            completeness: number;
            /** Missing */
            missing: string[];
            /** Updated At */
            updated_at?: string | null;
        };
        /** ClientCreateIn */
        ClientCreateIn: {
            /** Name */
            name: string;
        };
        /** ClientOut */
        ClientOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /**
         * CompanyEnrichIn
         * @description Refresh Apollo firmographics (the 'Update Field' button) for an explicit set of selected
         *     companies — re-enrich each row's industry/size/country/evidence on demand. This is the
         *     deliberate credit spend; find-company only enriches NEW rows to avoid paying twice per org.
         */
        CompanyEnrichIn: {
            /** Ids */
            ids?: string[];
        };
        /**
         * CompanyEnrichment
         * @description The 8 Apollo-enrich fields surfaced for user study (the "Enrichment" column), normalized
         *     from `Company.evidence`. All optional — an un-enriched / manual row carries empty values.
         */
        CompanyEnrichment: {
            /**
             * Short Description
             * @default
             */
            short_description: string;
            /**
             * Industries
             * @default []
             */
            industries: string[];
            /** Annual Revenue */
            annual_revenue?: number | null;
            /** Founded Year */
            founded_year?: number | null;
            /** Headcount Growth 12Mo */
            headcount_growth_12mo?: number | null;
            /**
             * Technologies
             * @default []
             */
            technologies: string[];
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /**
             * Hq
             * @default
             */
            hq: string;
        };
        /**
         * CompanyFindIn
         * @description Trigger Apollo Flow A (find companies) from the latest ResearchSpec. `limit` is capped to
         *     the spec's `credit_policy.max_companies` server-side.
         *
         *     `company_search_params`/`intent_filters` are an OPTIONAL operator override (the Settings modal):
         *     when present they replace the spec's blocks for *this call only* — the spec stays the AI source
         *     of truth, the override is the manual tuning. Omitted → the saved spec is used unchanged.
         */
        CompanyFindIn: {
            /**
             * Limit
             * @default 25
             */
            limit: number;
            /** Icp Id */
            icp_id?: string | null;
            /** Company Search Params */
            company_search_params?: {
                [key: string]: unknown;
            } | null;
            /** Intent Filters */
            intent_filters?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CompanyLookalikeIn
         * @description Find peers of the selected stage-1 rows (the 'Lookalike' button). The seeds are aggregated
         *     into an Apollo company-search filter HoldSlot-side (Apollo has no native lookalike API), then
         *     run through the normal Flow A tail — the seeds drop out by domain dedupe, so the result is the
         *     *next* batch. `icp_id` overrides the seeds' common ICP for fit scoring (omitted → inferred).
         */
        CompanyLookalikeIn: {
            /** Company Ids */
            company_ids?: string[];
            /** Icp Id */
            icp_id?: string | null;
        };
        /**
         * CompanyManualIn
         * @description Manually add one company (stage-1 gate) — same schema as a sourced row, `source=manual`.
         */
        CompanyManualIn: {
            /** Domain */
            domain: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Website
             * @default
             */
            website: string;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Industry
             * @default
             */
            industry: string;
            /**
             * Size
             * @default
             */
            size: string;
            /**
             * Country
             * @default
             */
            country: string;
            /** Icp Id */
            icp_id?: string | null;
        };
        /**
         * CompanyOut
         * @description One stage-1 Company-list row — firmographics + company-level fit, scoped to the client.
         */
        CompanyOut: {
            /** Id */
            id: string;
            /** Icp Id */
            icp_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Domain
             * @default
             */
            domain: string;
            /**
             * Website
             * @default
             */
            website: string;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Industry
             * @default
             */
            industry: string;
            /**
             * Size
             * @default
             */
            size: string;
            /**
             * Country
             * @default
             */
            country: string;
            /** Fit Score */
            fit_score?: number | null;
            /** Fit Tier */
            fit_tier?: string | null;
            /**
             * Fit Reason
             * @default
             */
            fit_reason: string;
            /**
             * Reason Tags
             * @default []
             */
            reason_tags: string[];
            enrichment?: components["schemas"]["CompanyEnrichment"];
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * CompanyRescoreIn
         * @description Re-run company fit scoring for an explicit set of already-sourced companies (the Step-1
         *     selection). Unlike find-company, this ignores the `fit_score is None` gate — it re-scores the
         *     given rows against the current rubric + scoring prompt so an existing list reflects a change.
         */
        CompanyRescoreIn: {
            /** Ids */
            ids?: string[];
        };
        /**
         * CompanySelectIn
         * @description Select/deselect stage-1 companies (scopes Flow B). `selected=False` reverts to discovered.
         */
        CompanySelectIn: {
            /** Ids */
            ids?: string[];
            /**
             * Selected
             * @default true
             */
            selected: boolean;
        };
        /**
         * DepartmentFacet
         * @description A master department row (with count) + its selectable subdepartment options. Only the 14
         *     masters are probed for counts, to bound the request to 11 + 14 free calls; subs are
         *     selection-only (the operator can refine to a subdepartment, but it shows no live count).
         */
        DepartmentFacet: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Subs */
            subs?: components["schemas"]["FacetOption"][];
        };
        /**
         * EnrichIn
         * @description Confirm which scored people to enrich (the enrich gate) by identity key.
         */
        EnrichIn: {
            /** Identity Keys */
            identity_keys?: string[];
        };
        /**
         * EnrichResult
         * @description Enrich-gate result — how many rows were enriched (Apollo people/match) + credits spent.
         *
         *     `failed` counts rows whose match call errored or had no Apollo match; the spend counts are
         *     always returned (never lost to a mid-batch failure) so the caller can reconcile the charge.
         */
        EnrichResult: {
            /** Confirmed */
            confirmed: number;
            /**
             * Enriched
             * @default 0
             */
            enriched: number;
            /**
             * Credits Spent
             * @default 0
             */
            credits_spent: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
        };
        /**
         * FacetCount
         * @description A facet value with its live people count in scope.
         */
        FacetCount: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /**
         * FacetOption
         * @description A selectable Apollo facet value + its human label (no count).
         */
        FacetOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /**
         * FindResult
         * @description Result of a find run: the run id + counts + the rows that landed (best fit first).
         */
        FindResult: {
            /** Run Id */
            run_id: string;
            /** Found */
            found: number;
            /** Dropped */
            dropped: number;
            /**
             * Companies
             * @default []
             */
            companies: components["schemas"]["CompanyOut"][];
            /**
             * Prospects
             * @default []
             */
            prospects: components["schemas"]["ProspectOut"][];
        };
        /**
         * FitPromptOut
         * @description The exact system + input prompt a company fit-score call would send (preview, no LLM call).
         *
         *     Mirrors the scoping-prompt preview, but for stage-1 company scoring: `user` carries the real
         *     TARGETING CONTEXT (this client's brief + research spec + ICP docs from the DB) plus the sample
         *     company, so the Fit-rubric modal shows what actually reaches the model. `company` names the
         *     sample row used; null when the tenant has no companies yet.
         */
        FitPromptOut: {
            /** System */
            system: string;
            /** User */
            user: string;
            /** Company */
            company?: string | null;
            /** Model */
            model: string[];
            /** Purpose */
            purpose: string;
            /** Prompt Version */
            prompt_version: string;
        };
        /** ForgotIn */
        ForgotIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IcpIn
         * @description An ICP profile — `name`/`tag` are the card header; `data` the opaque form document.
         */
        IcpIn: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Tag
             * @default
             */
            tag: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /** IcpOut */
        IcpOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tag */
            tag: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Updated At */
            updated_at?: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Clients */
            clients: components["schemas"]["ClientOut"][];
        };
        /**
         * PeopleFacetsIn
         * @description Compute the live Find-Settings facet sidebar for an explicit set of Step-2 companies.
         *
         *     Counts are scoped to the union of the selected companies' Apollo orgs (one `organization_ids`
         *     array) and computed PER facet value — exactly Apollo's UI sidebar ("Manager (9), Senior (3)…").
         *     Free: people search costs no credits. `company_ids` are Company.id; companies without an Apollo
         *     org id are ignored.
         */
        PeopleFacetsIn: {
            /** Company Ids */
            company_ids?: string[];
        };
        /**
         * PeopleFacetsOut
         * @description The facet sidebar: total people in scope + per-Management-Level and per-Department counts.
         */
        PeopleFacetsOut: {
            /** Total */
            total: number;
            /** Seniorities */
            seniorities: components["schemas"]["FacetCount"][];
            /** Departments */
            departments: components["schemas"]["DepartmentFacet"][];
        };
        /**
         * PeopleFindIn
         * @description Trigger Apollo Flow B (find people) across an explicit set of Step-2 companies. `per_company`
         *     is how many people each org contributes (one api_search call per org); the default fetches
         *     everyone matching the Find Settings, up to Apollo's 100-per-call max — no artificial 10 cap.
         *
         *     `company_ids` are the Step-2 rows to search, by Company.id. The search is driven by this set —
         *     NOT a server-side "selected" status — so an already-searched company can be re-searched and a
         *     0-result company is never permanently burned. Rows land UNSCORED ("Pending"); the operator
         *     scores on demand via the Step-2 'Get AI score' button (`/prospects/rescore`).
         *
         *     `people_search_params` is an OPTIONAL operator override (the Step-2 Settings modal): when
         *     present it replaces the spec's people block for *this call only* (`organization_ids` is still
         *     set per-org by the loop, never by the override). Omitted → the saved spec is used unchanged.
         */
        PeopleFindIn: {
            /**
             * Per Company
             * @default 100
             */
            per_company: number;
            /** Icp Id */
            icp_id?: string | null;
            /** People Search Params */
            people_search_params?: {
                [key: string]: unknown;
            } | null;
            /** Company Ids */
            company_ids?: string[];
        };
        /**
         * PeopleScopeOverrideIn
         * @description Save the Step-2 Find Settings as the tenant's persisted people-scope override. The payload is
         *     the Apollo people block (seniority/department facets) the modal produced; an empty object clears
         *     nothing — call DELETE to revert to the AI scope.
         */
        PeopleScopeOverrideIn: {
            /** People Search Params */
            people_search_params?: {
                [key: string]: unknown;
            };
        };
        /**
         * PeopleScopeOverrideOut
         * @description The persisted Step-2 override, or `null` params when none is saved (→ use the AI scope).
         */
        PeopleScopeOverrideOut: {
            /** People Search Params */
            people_search_params?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProspectManualIn
         * @description Manually add one person (stage-2 gate) — same schema as a sourced row, `source=manual`.
         */
        ProspectManualIn: {
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Domain
             * @default
             */
            domain: string;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Seniority
             * @default
             */
            seniority: string;
            /**
             * Company Industry
             * @default
             */
            company_industry: string;
            /**
             * Company Size
             * @default
             */
            company_size: string;
            /** Icp Id */
            icp_id?: string | null;
        };
        /**
         * ProspectOut
         * @description One Prospect-list row — fit context + source, scoped to the caller's client.
         */
        ProspectOut: {
            /** Id */
            id: string;
            /** Identity Key */
            identity_key: string;
            /** Icp Id */
            icp_id?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /**
             * Company
             * @default
             */
            company: string;
            /**
             * Domain
             * @default
             */
            domain: string;
            /**
             * Linkedin Url
             * @default
             */
            linkedin_url: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Email Valid
             * @default false
             */
            email_valid: boolean;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Company Industry
             * @default
             */
            company_industry: string;
            /**
             * Company Size
             * @default
             */
            company_size: string;
            /** Fit Score */
            fit_score?: number | null;
            /** Fit Tier */
            fit_tier?: string | null;
            /**
             * Fit Reason
             * @default
             */
            fit_reason: string;
            /**
             * Reason Tags
             * @default []
             */
            reason_tags: string[];
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ProspectRescoreIn
         * @description Re-run people fit scoring for an explicit set of already-found prospects (by identity key) —
         *     the Step-2 'Get AI score' button. Mirrors CompanyRescoreIn: re-scores against the current rubric
         *     regardless of whether the row was scored, so the people list reflects a rubric change.
         */
        ProspectRescoreIn: {
            /** Identity Keys */
            identity_keys?: string[];
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * ResearchJobOut
         * @description Status of the async structuring job: the `POST /brief/structure` 202 body + the poll target.
         *
         *     `status` ∈ idle | queued | running | done | error. `idle` = none has ever run; `spec_version`
         *     is set on `done` (the new ResearchSpec version to load); `error` carries a short cause on fail.
         */
        ResearchJobOut: {
            /** Job Id */
            job_id?: string | null;
            /** Status */
            status: string;
            /** Spec Version */
            spec_version?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ResearchRunOut
         * @description One research run; `cost_per_accepted` is the derived $/accepted.
         */
        ResearchRunOut: {
            /** Run Id */
            run_id: string;
            /** Source */
            source: string;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Rubric Version */
            rubric_version?: string | null;
            /** Rows Pushed */
            rows_pushed: number;
            /** Rows Accepted */
            rows_accepted: number;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Cost Per Accepted */
            cost_per_accepted?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ResearchSpecList
         * @description The latest spec plus the version history (newest first) for the review panel.
         */
        ResearchSpecList: {
            latest?: components["schemas"]["ResearchSpecOut"] | null;
            /**
             * Versions
             * @default []
             */
            versions: number[];
        };
        /**
         * ResearchSpecOut
         * @description A persisted ResearchSpec version, traceable to the LLM call that produced it.
         */
        ResearchSpecOut: {
            /** Version */
            version: number;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
            /** Gaps */
            gaps: {
                [key: string]: unknown;
            }[];
            /**
             * Icp Suggestions
             * @default []
             */
            icp_suggestions: {
                [key: string]: unknown;
            }[];
            /** Model */
            model?: string | null;
            /** Llm Call Id */
            llm_call_id?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ResetIn */
        ResetIn: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ScopingPromptOut
         * @description The exact LLM prompt that `POST /brief/structure` would send — for operator inspection.
         *
         *     Built from the same `build_messages(brief, icps)` the live call uses (single source of
         *     truth), but without making (or billing) the completion. The prompt-preview popup renders it.
         *     `system` is the effective system prompt (operator override if saved, else the default);
         *     `system_is_custom` says which. `user` is read-only — it is always the client brief + ICPs.
         */
        ScopingPromptOut: {
            /** System */
            system: string;
            /** User */
            user: string;
            /**
             * System Is Custom
             * @default false
             */
            system_is_custom: boolean;
            /** Model */
            model: string[];
            /** Purpose */
            purpose: string;
            /** Prompt Version */
            prompt_version: string;
        };
        /**
         * SourcingDocIn
         * @description Save the founder's edit as the next version of a fit rubric
         *     (`company_fit` | `prospect_fit`).
         */
        SourcingDocIn: {
            /** Stage */
            stage: string;
            /** Body */
            body: string;
        };
        /**
         * SourcingDocList
         * @description Latest version of each editable fit rubric: `company_fit` (Step 1) and
         *     `prospect_fit` (Step 2).
         */
        SourcingDocList: {
            company_fit?: components["schemas"]["SourcingDocOut"] | null;
            prospect_fit?: components["schemas"]["SourcingDocOut"] | null;
        };
        /** SourcingDocOut */
        SourcingDocOut: {
            /** Stage */
            stage: string;
            /** Version */
            version: number;
            /** Body */
            body: string;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * SystemPromptIn
         * @description An operator-edited system prompt for the scoping call, saved per client (versioned).
         */
        SystemPromptIn: {
            /** System */
            system: string;
        };
        /**
         * SystemPromptOut
         * @description The saved system prompt + its version after a save (or the effective one on read).
         */
        SystemPromptOut: {
            /** System */
            system: string;
            /** Version */
            version: number;
            /** Is Custom */
            is_custom: boolean;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_auth_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_auth_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_clients_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"][];
                };
            };
        };
    };
    create_client_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_context__client__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
        };
    };
    get_brief__client__brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefOut"];
                };
            };
        };
    };
    put_brief__client__brief_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_structure_prompt__client__brief_structure_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopingPromptOut"];
                };
            };
        };
    };
    save_system_prompt__client__brief_structure_system_prompt_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemPromptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemPromptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    structure_brief__client__brief_structure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchJobOut"];
                };
            };
        };
    };
    structure_status__client__brief_structure_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchJobOut"];
                };
            };
        };
    };
    get_research_spec__client__research_spec_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSpecList"];
                };
            };
        };
    };
    list_icps__client__icps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcpOut"][];
                };
            };
        };
    };
    create_icp__client__icps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IcpIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcpOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_icp__client__icps__icp_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                icp_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IcpIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcpOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_icp__client__icps__icp_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                icp_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prospects__client__prospects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectOut"][];
                };
            };
        };
    };
    add_prospect__client__prospects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProspectManualIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies__client__companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
        };
    };
    add_company__client__companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyManualIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_company__client__companies_find_company_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyFindIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_lookalikes__client__companies_find_lookalikes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyLookalikeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_companies__client__companies_select_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanySelectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_fit_prompt__client__fit_prompt_get: {
        parameters: {
            query?: {
                stage?: string;
                sample_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitPromptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescore_companies__client__companies_rescore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyRescoreIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_fields__client__companies_update_fields_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyEnrichIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_runs__client__research_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunOut"][];
                };
            };
        };
    };
    get_sourcing_docs__client__sourcing_docs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcingDocList"];
                };
            };
        };
    };
    save_sourcing_doc__client__sourcing_docs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcingDocIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcingDocOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_people__client__people_find_people_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeopleFindIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_facets__client__people_facets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeopleFacetsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleFacetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_people_scope_override__client__people_scope_override_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleScopeOverrideOut"];
                };
            };
        };
    };
    save_people_scope_override__client__people_scope_override_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeopleScopeOverrideIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleScopeOverrideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_people_scope_override__client__people_scope_override_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    people_departments__client__people_departments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetOption"][];
                };
            };
        };
    };
    rescore_prospects__client__prospects_rescore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProspectRescoreIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_enrich__client__prospects_enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
